USE [master]
GO

/****** Object:  Database [Lithium]    Script Date: 04/09/2013 14:29:34 ******/
CREATE DATABASE [Lithium] ON  PRIMARY 
( NAME = N'Lithium', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\Lithium.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Lithium_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\Lithium_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Lithium] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Lithium].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Lithium] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Lithium] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Lithium] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Lithium] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Lithium] SET ARITHABORT OFF 
GO

ALTER DATABASE [Lithium] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Lithium] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Lithium] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Lithium] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Lithium] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Lithium] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Lithium] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Lithium] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Lithium] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Lithium] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Lithium] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Lithium] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Lithium] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Lithium] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Lithium] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Lithium] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Lithium] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Lithium] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Lithium] SET  READ_WRITE 
GO

ALTER DATABASE [Lithium] SET RECOVERY FULL 
GO

ALTER DATABASE [Lithium] SET  MULTI_USER 
GO

ALTER DATABASE [Lithium] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Lithium] SET DB_CHAINING OFF 
GO


USE [Lithium]
GO

/****** Object:  Table [dbo].[Member]    Script Date: 04/09/2013 14:30:09 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Member](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NULL,
	[Username] [nvarchar](50) NULL,
	[SomeEnum] [int] NOT NULL,
 CONSTRAINT [PK_Member] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


USE [Lithium]
GO

/****** Object:  Table [dbo].[MemberIgnore]    Script Date: 04/09/2013 14:30:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MemberIgnore](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NULL,
	[Username] [nvarchar](50) NULL,
 CONSTRAINT [PK_MemberIgnore] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


USE [Lithium]
GO

/****** Object:  StoredProcedure [dbo].[OutputParameters]    Script Date: 04/09/2013 14:30:40 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create procedure [dbo].[OutputParameters]
	@outputInt int output,
	@outputString nvarchar(max) output
as
set @outputInt = 1337
set @outputString = 'asdf'

GO


USE [Lithium]
GO

/****** Object:  StoredProcedure [dbo].[ReturnValue]    Script Date: 04/09/2013 14:30:47 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE procedure [dbo].[ReturnValue]
as
return 11

GO

